ucsb-cs156-f23/team03-f23-5pm-3

README.md

Update readme links and title
Deployments:
* Prod: <https://team03.dokku-03.cs.ucsb.edu >
* QA: <https://team03-qa.dokku-03.cs.ucsb.edu>
Closes #5

liv - Update readme links and title

---

src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestControllerTests.java

Added entity, controller, controller tests and repository for RecommendationRequest.
Closes #26

ky - copied files for backend CRUD API RecommendationRequests

---

src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java
src/main/java/edu/ucsb/cs156/example/entities/Articles.java
src/main/java/edu/ucsb/cs156/example/repositories/ArticlesRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/ArticlesControllerTests.java

Tested on Swagger on dokku and localhost and Articles backend CRUD operations show up
Closes #53

Copied over files for Backend CRUD API for Articles database table

---

src/main/java/edu/ucsb/cs156/example/controllers/HelpRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/HelpRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/HelpRequestRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/HelpRequestControllerTests.java

Copy files for Backend CRUD API HelpRequest from team02
Closes #44

liv - Copy files for Backend CRUD API HelpRequest from team02

---

frontend/src/fixtures/helpRequestFixtures.js
src/main/java/edu/ucsb/cs156/example/controllers/HelpRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/HelpRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/HelpRequestRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/HelpRequestControllerTests.java

Create fixtures for HelpRequest
Closes #45

liv - Create fixtures for HelpRequest

---

src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java

I Copied files for Backend CRUD API UCSBOrganization from team02
closes #17

Kailtyn-Copy files for Backend CRUD API UCSBOrganization from team02

---

frontend/src/fixtures/ucsbDiningCommonsMenuItemFixtures.js

Created fixures for UCSBDiningCommonsMenuItems.
Closes #9

added UCSBDiningCommonsMenuItems fixtures

---

frontend/src/fixtures/ucsbOrganizationFixtures.js

I created fixtures for UCSBOrganization.
closes #18

Kaitlyn-fixtures for ucsborg

---

frontend/src/fixtures/articlesFixtures.js

added articles fixtures for testing

---

frontend/src/App.js
frontend/src/fixtures/ucsbDiningCommonsMenuItemFixtures.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js
frontend/src/tests/components/Nav/AppNavbar.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js

Added placeholders for UCSB Dining Commons Menu Item and tests and updated Navbar.
Closes #12

Added placeholders for UCSB Dining Commons Menu Item 

---

frontend/src/main/components/HelpRequest/HelpRequestForm.js
frontend/src/stories/components/HelpRequest/HelpRequestForm.stories.js
frontend/src/tests/components/HelpRequest/HelpRequestForm.test.js

Added HelpRequest Form Component plus tests
Link to storybook: https://ucsb-cs156-f23.github.io/team03-f23-5pm-3/prs/79/storybook/?path=/story/components-helprequest-helprequestform--create
Closes #46

Oj - Add HelpRequest Form Component plus tests

---

frontend/src/fixtures/articlesFixtures.js
frontend/src/main/components/Articles/ArticlesForm.js
frontend/src/stories/components/Articles/ArticlesForm.stories.js
frontend/src/tests/components/Articles/ArticlesForm.test.js

https://ucsb-cs156-f23.github.io/team03-f23-5pm-3/prs/80/storybook/?path=/story/components-articles-articlesform--create
Closes #55

Implemented the articles form and tests

---

frontend/src/App.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js
frontend/src/stories/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.stories.js
frontend/src/tests/components/Nav/AppNavbar.test.js
frontend/src/tests/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js

Added the UCSB Dining Commons Menu Item Form, tests, and story
https://ucsb-cs156-f23.github.io/team03-f23-5pm-3/prs/78/storybook/?path=/story/components-ucsbdiningcommonsmenuitem-ucsbdiningcommonsmenuitemform--create 
Closes #10

Created the UCSB Dining Commons Menu Item Form

---

frontend/src/fixtures/articlesFixtures.js
frontend/src/main/components/Articles/ArticlesForm.js
frontend/src/main/components/Articles/ArticlesTable.js
frontend/src/main/utils/articlesUtils.js
frontend/src/stories/components/Articles/ArticlesForm.stories.js
frontend/src/stories/components/Articles/ArticlesTable.stories.js
frontend/src/tests/components/Articles/ArticlesForm.test.js
frontend/src/tests/components/Articles/ArticlesTable.test.js
frontend/src/tests/utils/articlesUtils.test.js

https://ucsb-cs156-f23.github.io/team03-f23-5pm-3/prs/82/storybook/?path=/story/components-articles-articlestable--empty
Closes #56

Created the Articles table and associated tests in the frontend

---

frontend/src/App.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/HelpRequest/HelpRequestCreatePage.js
frontend/src/main/pages/HelpRequest/HelpRequestEditPage.js
frontend/src/main/pages/HelpRequest/HelpRequestIndexPage.js
frontend/src/tests/pages/HelpRequest/HelpRequestCreatePage.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestEditPage.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestIndexPage.test.js

Placeholder changes to new branch for HelpRequest
Copy Placeholders for HelpRequest pages; add to App.js/AppNavbar.js
Closes #48

oj - remade HelpRequest Placeholders

---

frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js
frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.stories.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js

Added UCSB Dining Commons Menu Item Page, tests, and story.
https://ucsb-cs156-f23.github.io/team03-f23-5pm-3/prs/87/storybook/?path=/story/pages-ucsbdiningcommonsmenuitem-ucsbdiningcommonsmenuitemindexpage--three-items-ordinary-user 
Close #14

Created UCSB Dining Commons Menu Item Index Page

---

frontend/src/App.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/Articles/ArticlesCreatePage.js
frontend/src/main/pages/Articles/ArticlesEditPage.js
frontend/src/main/pages/Articles/ArticlesIndexPage.js
frontend/src/tests/pages/Articles/ArticlesCreatePage.test.js
frontend/src/tests/pages/Articles/ArticlesEditPage.test.js
frontend/src/tests/pages/Articles/ArticlesIndexPage.test.js

Added placeholders for articles pages along with tests

---

frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationForm.stories.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationForm.test.js

It passed on styker and locally and looks decent on storybook
closes #19

Kaitlyn-Org-form and test done

---

frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js
frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.stories.js
frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.stories.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js

Created UCSB Dining Commons Menu Item Create Page, test, and story.
https://ucsb-cs156-f23.github.io/team03-f23-5pm-3/prs/91/storybook/?path=/story/pages-ucsbdiningcommonsmenuitem-ucsbdiningcommonsmenuitemcreatepage--default
Closes #13

Added UCSB Dining Commons Menu Item Create Page

---

frontend/src/App.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js
frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js
frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.stories.js
frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.stories.js
frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.stories.js
frontend/src/tests/components/Nav/AppNavbar.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js
frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js

Added UCSB Dining Commons Menu Item Edit Page, tests, and stories.
Closes #15

Created UCSB Dining Commons Menu Item Edit Page

---

frontend/src/fixtures/ucsbOrganizationFixtures.js
frontend/src/main/components/UCSBOrganization/UCSBOrganizationTable.js
frontend/src/main/utils/UCSBOrganizationUtils.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationTable.stories.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationTable.test.js
frontend/src/tests/utils/UCSBOrganization.test.js

http://localhost:6006/?path=/story/components-ucsborganization-ucsborganizationtable--three-items-admin-user
I did the Table Component for UCSBOrganization plus tests.
closes #20

Kaitlyn-Table Component for UCSBOrganization plus tests

---

frontend/src/main/components/HelpRequest/HelpRequestTable.js
frontend/src/main/utils/HelpRequestUtils.js
frontend/src/stories/components/HelpRequest/HelpRequestTable.stories.js
frontend/src/tests/components/HelpRequest/HelpRequestTable.test.js
frontend/src/tests/utils/HelpRequestUtils.test.js

Table Component for HelpRequest + tests
Link to storybook: https://ucsb-cs156-f23.github.io/team03-f23-5pm-3/prs/98/storybook/?path=/story/components-helprequest-helprequesttable--three-items-admin-user
Closes #47

oj - passed all local tests for HelpRequestTable

---

frontend/src/main/components/HelpRequest/HelpRequestTable.js
frontend/src/main/pages/HelpRequest/HelpRequestCreatePage.js
frontend/src/main/utils/HelpRequestUtils.js
frontend/src/stories/components/HelpRequest/HelpRequestTable.stories.js
frontend/src/stories/pages/HelpRequest/HelpRequestCreatePage.stories.js
frontend/src/tests/components/HelpRequest/HelpRequestTable.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestCreatePage.test.js
frontend/src/tests/utils/HelpRequestUtils.test.js

HelpRequest create page, plus tests and stories
Storybook link: 
Steps to test: 
- input all valid parameters: email, team (of the form f23-5pm-3), table or breakout room, Time (iso format), Explanation, and Solved (true/false)
Functioning correctly: 
Closes: #49

Oj - HelpRequest create page, plus tests and stories

---

frontend/src/main/pages/Articles/ArticlesCreatePage.js
frontend/src/main/pages/Articles/ArticlesEditPage.js
frontend/src/main/pages/Articles/ArticlesIndexPage.js
frontend/src/stories/pages/Articles/ArticlesCreatePage.stories.js
frontend/src/stories/pages/Articles/ArticlesEditPage.stories.js
frontend/src/stories/pages/Articles/ArticlesIndexPage.stories.js
frontend/src/tests/pages/Articles/ArticlesCreatePage.test.js
frontend/src/tests/pages/Articles/ArticlesEditPage.test.js
frontend/src/tests/pages/Articles/ArticlesIndexPage.test.js

Added articles edit page and associated tests
Closes #60

Wyatt articles edit page

---

frontend/src/main/pages/Articles/ArticlesCreatePage.js
frontend/src/stories/pages/Articles/ArticlesCreatePage.stories.js
frontend/src/tests/pages/Articles/ArticlesCreatePage.test.js

https://ucsb-cs156-f23.github.io/team03-f23-5pm-3/prs/103/storybook/?path=/story/pages-articles-articlescreatepage--default
1. /articles/create should be the create page
2. It should allow creation of a new valid article and this should show up in the database
3. It should redirect to the not yet implemented articles index page
Closes #58

Added articles create page and associated tests

---

frontend/src/main/pages/Articles/ArticlesCreatePage.js
frontend/src/main/pages/Articles/ArticlesIndexPage.js
frontend/src/stories/pages/Articles/ArticlesCreatePage.stories.js
frontend/src/stories/pages/Articles/ArticlesIndexPage.stories.js
frontend/src/tests/pages/Articles/ArticlesCreatePage.test.js
frontend/src/tests/pages/Articles/ArticlesIndexPage.test.js

Implemented the Articles Index page and associated tests
Closes #59

Wyatt articles index page

---

frontend/src/App.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationCreatePage.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationEditPage.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationIndexPage.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationCreatePage.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationEditPage.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationIndexPage.test.js

Added the placeholders, if you approve my table first, then it should go thru.
closes #21

Kaitlyn - Copy placeholders done

---

frontend/src/main/pages/HelpRequest/HelpRequestIndexPage.js
frontend/src/stories/pages/HelpRequest/HelpRequestIndexPage.stories.js
frontend/src/tests/pages/HelpRequest/HelpRequestIndexPage.test.js

HelpRequest Index Page, plus tests and stories
Storybook: https://ucsb-cs156-f23.github.io/team03-f23-5pm-3/prs/102/storybook/?path=/story/pages-helprequest-helprequestindexpage--empty
Closes #50

oj - HelpRequest Index Page, plus tests and stories

---

frontend/src/App.js
frontend/src/main/pages/MenuItemReview/MenuItemReviewCreatePage.js
frontend/src/main/pages/MenuItemReview/MenuItemReviewEditPage.js
frontend/src/main/pages/MenuItemReview/MenuItemReviewIndexPage.js
frontend/src/stories/pages/MenuItemReview/MenuItemReviewCreatePage.stories.js
frontend/src/stories/pages/MenuItemReview/MenuItemReviewEditPage.stories.js
frontend/src/stories/pages/MenuItemReview/MenuItemReviewIndexPage.stories.js
frontend/src/tests/pages/MenuItemReview/MenuItemReviewCreatePage.test.js
frontend/src/tests/pages/MenuItemReview/MenuItemReviewEditPage.test.js
frontend/src/tests/pages/MenuItemReview/MenuItemReviewIndexPage.test.js

Instructions:
Navigate to MenuItemReview in the Navbar
Select Create MenuItemReview
Fill out the parameters
Click Submit, you should get a success message 
If you want to delete a MenuitemReview,
Do the same but select edit and submit,
Check swagger to ensure the update occurred correctly 
https://ucsb-cs156-f23.github.io/team03-f23-5pm-3/storybook/?path=/story/components-menuitemreview-menuitemreviewform--create

MenuItemReview, Edit, closes @41

---

frontend/src/App.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationCreatePage.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationIndexPage.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationForm.stories.js
frontend/src/stories/pages/UCSBOrganization/UCSBOrganizationCreatePage.stories.js
frontend/src/stories/pages/UCSBOrganization/UCSBOrganizationIndexPage.stories.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationForm.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationCreatePage.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationIndexPage.test.js

I completed the index page, test, and story as shown below.
closes #23

Kaitlyn org index done

---

frontend/src/main/pages/HelpRequest/HelpRequestEditPage.js
frontend/src/stories/pages/HelpRequest/HelpRequestEditPage.stories.js
frontend/src/tests/pages/HelpRequest/HelpRequestEditPage.test.js

Add HelpRequest Edit Page plus tests and stories
Storybook:https://ucsb-cs156-f23.github.io/team03-f23-5pm-3/prs/108/storybook/?path=/story/pages-helprequest-helprequesteditpage--default
Closes #51

Oj - HelpRequest Edit Page plus tests and stories

---

frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationEditPage.js
frontend/src/stories/pages/UCSBOrganization/UCSBOrganizationEditPage.stories.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationEditPage.test.js

https://ucsb-cs156-f23.github.io/team03-f23-5pm-3/prs/109/storybook/?path=/story/pages-ucsborganization-ucsborganizationeditpage--default
It passed all the tests locally.
This is the edit page, test and story.
closes #24

Kaitlyn Organization Edit Page test and story

---

frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
frontend/src/stories/components/RecommendationRequest/RecommendationRequestForm.stories.js
frontend/src/tests/components/RecommendationRequest/RecommendationRequestForm.test.js

Created recommendation request form with input fields requester email, professor email, explanation date requested, date needed, and done.

ky - finished recommendation request form

---

frontend/src/App.js
frontend/src/fixtures/recommendationRequestFixtures.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js
frontend/src/main/pages/RecommendationRequest/RecommendationRequestCreatePage.js
frontend/src/main/pages/RecommendationRequest/RecommendationRequestEditPage.js
frontend/src/main/pages/RecommendationRequest/RecommendationRequestIndexPage.js
frontend/src/main/utils/recommendationRequestUtils.js
frontend/src/stories/pages/RecommendationRequest/RecommendationRequestCreatePage.stories.js
frontend/src/stories/pages/RecommendationRequest/RecommendationRequestEditPage.stories.js
frontend/src/stories/pages/RecommendationRequest/RecommendationRequestIndexPage.stories.js
frontend/src/tests/components/RecommendationRequest/RecommendationRequestForm.test.js
frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js
frontend/src/tests/pages/RecommendationRequest/RecommendationRequestCreatePage.test.js
frontend/src/tests/pages/RecommendationRequest/RecommendationRequestEditPage.test.js
frontend/src/tests/pages/RecommendationRequest/RecommendationRequestIndexPage.test.js
frontend/src/tests/utils/recommendationRequestUtils.test.js

Added placeholder pages and test for create, edit, and index pages.

ky - added placeholder recommendation request pages

---

frontend/src/fixtures/recommendationRequestFixtures.js

Boolean values were not appearing in table - fixed.

ky - recommendation request table fix

---

frontend/src/fixtures/ucsbOrganizationFixtures.js
frontend/src/main/components/UCSBOrganization/UCSBOrganizationTable.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationCreatePage.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationEditPage.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationTable.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationCreatePage.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationEditPage.test.js

I solved one problem but there is still the linker error I am getting which I will probably ask for help tommorow

Kaitlyn fixes

---

frontend/src/App.js
frontend/src/fixtures/helpRequestFixtures.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/HelpRequest/HelpRequestCreatePage.js
frontend/src/main/pages/HelpRequest/HelpRequestEditPage.js
frontend/src/main/pages/HelpRequest/HelpRequestIndexPage.js
frontend/src/tests/pages/HelpRequest/HelpRequestCreatePage.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestEditPage.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestIndexPage.test.js

Liv - fixed HelpRequest table not showing up after clicking Create and Edit

Liv - HelpRequest Table fixes

---

frontend/src/App.js

Please approve. There was an error with the endpoint for App.js

Changed app.js because endpoint was wrong

---

frontend/src/main/components/HelpRequest/HelpRequestForm.js
frontend/src/main/pages/HelpRequest/HelpRequestEditPage.js
frontend/src/tests/components/HelpRequest/HelpRequestForm.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestEditPage.test.js

Liv - HelpRequest fixes for edit

---

frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js
frontend/src/main/pages/RecommendationRequest/RecommendationRequestCreatePage.js
frontend/src/tests/pages/RecommendationRequest/RecommendationRequestCreatePage.test.js

The "done" status of each row (a singular recommendation request) was not appearing. Fixed the boolean display issue in the tables.

ky - fixed done field in recommendation request

---

frontend/src/main/components/HelpRequest/HelpRequestForm.js
frontend/src/tests/components/HelpRequest/HelpRequestForm.test.js

fixed requestTime field for HelpRequest from text input to a date time picker (like UCSB date)

oj - fixed time field to match UCSB date's time picker
